import "~/styles/globals.css";

import { type Metadata } from "next";
import { Toaster } from "sonner";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
    title: "Legacy App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/logo.png" }],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <head>
                {/* Pre-hydration theme script to prevent FOUC */}
                <script
                    dangerouslySetInnerHTML={{
                        __html: `
                            (function() {
                                const theme = localStorage.getItem('theme');
                                const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
                                const isDark = theme === 'dark' || (!theme && prefersDark);
                                if (isDark) {
                                    document.documentElement.classList.add('dark');
                                } else {
                                    document.documentElement.classList.remove('dark');
                                }
                            })();
                        `,
                    }}
                />
            </head>
            <body>
                <TRPCReactProvider>{children}</TRPCReactProvider>
                <Toaster position="bottom-right" />
            </body>
        </html>
    );
}
