import "~/styles/globals.css";

import { type Metadata } from "next";
import { Toaster } from "sonner";

import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
    title: "Legacy App",
    description: "Generated by create-t3-app",
    icons: [{ rel: "icon", url: "/logo.png" }],
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body>
                <TRPCReactProvider>{children}</TRPCReactProvider>
                <Toaster position="bottom-right" />
            </body>
        </html>
    );
}
